// File automatically generated by swift-bridge.
#include <stdbool.h>
void __swift_bridge__$print_hello_rust(void);
bool __swift_bridge__$is_from_rust(void);
void* __swift_bridge__$get_hello_rust(void);


